swagger: '2.0'
info:
  version: '1.0'
  title: 'Ehgzly''s Application'
  description: >-
    Ehgzly application is one of the most succeeded startups in egypt, developed
    with love by Fawzi E. Abdulfattah. 
paths:
  /addMovie:
    post:
      tags:
      - "movies"
      summary: "Add New movie"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Required Information to add new movie"
        required: true
        schema:
          $ref: "#/definitions/add_movie_body"
      - in: "header"
        name: "authorization"
        required: true
        type: "string"
      responses:
        '200':
          description: 201 (Created - Movie Created Successfully)
          schema:
            $ref: '#/definitions/add_movie_response'
        '401':
          description: 401 (Unauthorized)
          schema:
            $ref: '#/definitions/error_401'
        '403':
          description: 403 (Forbidden - Your aren't authorized)
          schema:
            $ref: '#/definitions/error_403'
        '400':
          description: 400 (Bad Request - input is incorrect or missing)
          schema:
            $ref: '#/definitions/error_400'
  /signin:
    post:
      tags:
      - "users"
      summary: "Signin a user"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Required Information to sign a user"
        required: true
        schema:
          $ref: "#/definitions/signin_body"
      responses:
        '201':
          description: 201 (Success - User logined Successfully)
          schema:
            $ref: '#/definitions/signin_response'
        '401':
          description: 401 (Unauthorized - Phone number is not registered)
          schema:
            $ref: '#/definitions/error_401'
        '403':
          description: 403 (Forbidden - Phone number is blocked)
          schema:
            $ref: '#/definitions/error_403'
        '400':
          description: 400 (Bad Request - input is incorrect or missing)
          schema:
            $ref: '#/definitions/error_400'
  /signup:
    post:
      tags:
      - "users"
      summary: "Signup a new user"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Required Information to register a user"
        required: true
        schema:
          $ref: "#/definitions/signup_body"
      responses:
        '201':
          description: 201 (Created - User Created Successfully)
          schema:
            $ref: '#/definitions/signup_response'
        '409':
          description: 409 (CONFLICT - Phone number already registered)
          schema:
            $ref: '#/definitions/error_409'
        '400':
          description: 400 (Bad Request - input is incorrect or missing)
          schema:
            $ref: '#/definitions/error_400'
  /refresh_token:
    post:
      tags:
      - "users"
      summary: "To get a new token for specific user"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "header"
        name: "authorization"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Required Information to update the token"
        required: true
        schema:
          $ref: "#/definitions/refresh_token_body"
      responses:
        '200':
          description: 200 (Success - User's is updated successfully)
          schema:
            $ref: '#/definitions/refresh_token_response'
        '401':
          description: 401 (Unauthorized - Token is invalid or not provided - check the message -)
          schema:
            $ref: '#/definitions/error_401'
        '400':
          description: 400 (Bad Request - input is incorrect or missing)
          schema:
            $ref: '#/definitions/error_400'
definitions:
   add_movie_body:
    type: "object"
    example: 
      movie_name: The biggest one2
      cover: 'https://www.google.com2'
      category: action
      description: The best movie ever2
      rate: 4
   add_movie_response:
    type: "object"
    example: 
      status: true
      message: success
      data:
        movie_id: 1
        movie_name: The biggest one2
        cover: 'https://www.google.com2'
        category: action
        description: The best movie ever2
        rate: 4
   refresh_token_body:
    type: "object"
    example: 
      refresh_token: 41e553cbd60fe02aec0e575e350b3982
   refresh_token_response:
    type: "object"
    example: 
      status: true
      message: success
      data:
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZV9udW1iZXIiOiIwMTA5MDI0Mzc5OSIsInVzZXJfaWQiOjEzLCJpYXQiOjE1OTQzMzIyOTEsImV4cCI6MTU5NDM3NTQ5MX0.EUgO0wpAQNjiieE40EzqdTLewEqf5OWibt99-U1U5HI
   signin_body:
    type: "object"
    example: 
      phone_number: 01090243795
   signin_response:
    type: "object"
    example: 
      status: true
      message: success
      data:
        user_id: 13
        phone_number: 01090243795
        first_name: fawzi
        last_name: essam
        country: egypt
        city: portsaid
        wallet: 0
        firebase_token: '93484893983498'
        refresh_token: 41e553cbd60fe02aec0e575e350b3982
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZV9udW1iZXIiOiIwMTA5MDI0Mzc5OSIsInVzZXJfaWQiOjEzLCJpYXQiOjE1OTQzMzIyOTEsImV4cCI6MTU5NDM3NTQ5MX0.EUgO0wpAQNjiieE40EzqdTLewEqf5OWibt99-U1U5HI
   signup_body:
    type: "object"
    example: 
      phone_number: 01090243795
      first_name: fawzi
      last_name: essam
      country: egypt
      city: portsaid
      firebase_token: '93484893983498'
   signup_response:
    type: "object"
    example: 
      status: true
      message: success
      data:
        user_id: 13
        phone_number: 01090243795
        first_name: fawzi
        last_name: essam
        country: egypt
        city: portsaid
        wallet: 0
        firebase_token: '93484893983498'
        refresh_token: 41e553cbd60fe02aec0e575e350b3982
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZV9udW1iZXIiOiIwMTA5MDI0Mzc5OSIsInVzZXJfaWQiOjEzLCJpYXQiOjE1OTQzMzIyOTEsImV4cCI6MTU5NDM3NTQ5MX0.EUgO0wpAQNjiieE40EzqdTLewEqf5OWibt99-U1U5HI
      
   error_409:
    type: "object"
    description: "CONFLICT"
    example:
      status: false
      message: "Error explaniation will be shown here"
      data: []
  
   error_401:
    type: "string"
    description: "Unauthorized"
    example:
      status: false
      message: "Error explaniation will be shown here"
      data: []
   error_400:
    type: "string"
    description: "Bad Request"
    example:
      status: false
      message: "Error explaniation will be shown here"
      data: []
   error_403:
    type: "string"
    description: "Forbidden"
    example:
      status: false
      message: "Error explaniation will be shown here"
      data: []
