swagger: '2.0'
info:
  version: '1.0'
  title: 'Ehgzly''s Application'
  description: >-
    Ehgzly application is one of the most succeeded startups in egypt, developed
    with love by Fawzi E. Abdulfattah. 
host: "localhost:3000"
basePath: "/api"
paths:
  /signup:
    post:
      tags:
      - "users"
      summary: "Signup a new user"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Required Information to register a user"
        required: true
        schema:
          $ref: "#/definitions/signup_body"
      responses:
        '201':
          description: 201 (Created - User Created Successfully)
          schema:
            $ref: '#/definitions/signup_response'
        '409':
          description: 409 (CONFLICT - Phone number already registered)
          schema:
            $ref: '#/definitions/error_409'
        '400':
          description: 400 (Bad Request - input is incorrect or missing)
          schema:
            $ref: '#/definitions/error_400'
definitions:
 signup_body:
    type: "object"
    example: 
      phone_number: 01090243795
      first_name: fawzi
      last_name: essam
      country: egypt
      city: portsaid
      firebase_token: '93484893983498'
 signup_response:
    type: "object"
    example: 
      status: true
      message: success
      data:
        user_id: 44
        phone_number: 01090243795
        first_name: fawzi
        last_name: essam
        country: egypt
        city: portsaid
        firebase_token: '93484893983498'
        refresh_token: 9336763ce1bb99f2706cecaf0f4d0324
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZV9udW1iZXIiOiIwMTA5MDI0Mzc5NSIsInVzZXJfaWQiOjQ0LCJpYXQiOjE1OTQzMjUxNzYsImV4cCI6MTU5NDM2ODM3Nn0.pagVw5VMRVi2m4c7EeaZyYwdPgtTffoUSCYYUce8tcw
        latitude: 0
        longitude: 0
        wallet: 0
        updatedAt: '2020-07-09T20:06:16.912Z'
        createdAt: '2020-07-09T20:06:16.912Z'
 error_409:
    type: "object"
    description: "CONFLICT"
    example:
      status: true
      message: "Error explaniation will be shown here"
      data: []
  
 error_401:
    type: "string"
    description: "Unauthorized"
    example:
      status: true
      message: "Error explaniation will be shown here"
      data: []
 error_400:
    type: "string"
    description: "Bad Request"
    example:
      status: true
      message: "Error explaniation will be shown here"
      data: []
